src/java/com/vikas/LoginPage/presentation/LoginPageController.java
package com.vikas.LoginPage.presentation;

import com.vikas.LoginPage.LoginPage;
import com.vikas.LoginPage.presentation.util.JsfUtil;
import com.vikas.LoginPage.presentation.util.PaginationHelper;
import com.vikas.LoginPage.fascade.LoginPageFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("loginPageController")
@SessionScoped
public class LoginPageController implements Serializable {

    private LoginPage current;
    private DataModel items = null;
    @EJB
    private com.vikas.LoginPage.fascade.LoginPageFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public LoginPageController() {
    }

    public LoginPage getSelected() {
        if (current == null) {
            current = new LoginPage();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LoginPageFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (LoginPage) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new LoginPage();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LoginPageCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (LoginPage) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LoginPageUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (LoginPage) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LoginPageDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public LoginPage getLoginPage(java.lang.Long id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = LoginPage.class)
    public static class LoginPageControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LoginPageController controller = (LoginPageController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "loginPageController");
            return controller.getLoginPage(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof LoginPage) {
                LoginPage o = (LoginPage) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + LoginPage.class.getName());
            }
        }

    }

}

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="/ui/loginPage/List" value="Show All LoginPage Items"/>
    </h:body>

</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>

web/ui/loginPage/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateLoginPageTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateLoginPageLabel_email}" for="email" />
                    <h:inputText id="email" value="#{loginPageController.selected.email}" title="#{bundle.CreateLoginPageTitle_email}" />
                    <h:outputLabel value="#{bundle.CreateLoginPageLabel_lastName}" for="lastName" />
                    <h:inputText id="lastName" value="#{loginPageController.selected.lastName}" title="#{bundle.CreateLoginPageTitle_lastName}" />
                    <h:outputLabel value="#{bundle.CreateLoginPageLabel_firstName}" for="firstName" />
                    <h:inputText id="firstName" value="#{loginPageController.selected.firstName}" title="#{bundle.CreateLoginPageTitle_firstName}" />
                    <h:outputLabel value="#{bundle.CreateLoginPageLabel_id}" for="id" />
                    <h:inputText id="id" value="#{loginPageController.selected.id}" title="#{bundle.CreateLoginPageTitle_id}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{loginPageController.create}" value="#{bundle.CreateLoginPageSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{loginPageController.prepareList}" value="#{bundle.CreateLoginPageShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateLoginPageIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/ui/loginPage/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditLoginPageTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditLoginPageLabel_email}" for="email" />
                    <h:inputText id="email" value="#{loginPageController.selected.email}" title="#{bundle.EditLoginPageTitle_email}" />
                    <h:outputLabel value="#{bundle.EditLoginPageLabel_lastName}" for="lastName" />
                    <h:inputText id="lastName" value="#{loginPageController.selected.lastName}" title="#{bundle.EditLoginPageTitle_lastName}" />
                    <h:outputLabel value="#{bundle.EditLoginPageLabel_firstName}" for="firstName" />
                    <h:inputText id="firstName" value="#{loginPageController.selected.firstName}" title="#{bundle.EditLoginPageTitle_firstName}" />
                    <h:outputLabel value="#{bundle.EditLoginPageLabel_id}" for="id" />
                    <h:inputText id="id" value="#{loginPageController.selected.id}" title="#{bundle.EditLoginPageTitle_id}" />
                </h:panelGrid>
                <h:commandLink action="#{loginPageController.update}" value="#{bundle.EditLoginPageSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditLoginPageViewLink}"/>
                <br />
                <h:commandLink action="#{loginPageController.prepareList}" value="#{bundle.EditLoginPageShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditLoginPageIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/ui/loginPage/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListLoginPageTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListLoginPageEmpty}" rendered="#{loginPageController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{loginPageController.items.rowCount > 0}">
                    <h:outputText value="#{loginPageController.pagination.pageFirstItem + 1}..#{loginPageController.pagination.pageLastItem + 1}/#{loginPageController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{loginPageController.previous}" value="#{bundle.Previous} #{loginPageController.pagination.pageSize}" rendered="#{loginPageController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{loginPageController.next}" value="#{bundle.Next} #{loginPageController.pagination.pageSize}" rendered="#{loginPageController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{loginPageController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoginPageTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoginPageTitle_lastName}"/>
                            </f:facet>
                            <h:outputText value="#{item.lastName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoginPageTitle_firstName}"/>
                            </f:facet>
                            <h:outputText value="#{item.firstName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLoginPageTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{loginPageController.prepareView}" value="#{bundle.ListLoginPageViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{loginPageController.prepareEdit}" value="#{bundle.ListLoginPageEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{loginPageController.destroy}" value="#{bundle.ListLoginPageDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{loginPageController.prepareCreate}" value="#{bundle.ListLoginPageCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListLoginPageIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/ui/loginPage/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewLoginPageTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewLoginPageLabel_email}"/>
                    <h:outputText value="#{loginPageController.selected.email}" title="#{bundle.ViewLoginPageTitle_email}"/>
                    <h:outputText value="#{bundle.ViewLoginPageLabel_lastName}"/>
                    <h:outputText value="#{loginPageController.selected.lastName}" title="#{bundle.ViewLoginPageTitle_lastName}"/>
                    <h:outputText value="#{bundle.ViewLoginPageLabel_firstName}"/>
                    <h:outputText value="#{loginPageController.selected.firstName}" title="#{bundle.ViewLoginPageTitle_firstName}"/>
                    <h:outputText value="#{bundle.ViewLoginPageLabel_id}"/>
                    <h:outputText value="#{loginPageController.selected.id}" title="#{bundle.ViewLoginPageTitle_id}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{loginPageController.destroyAndView}" value="#{bundle.ViewLoginPageDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewLoginPageEditLink}"/>
                <br />
                <h:commandLink action="#{loginPageController.prepareCreate}" value="#{bundle.ViewLoginPageCreateLink}" />
                <br />
                <h:commandLink action="#{loginPageController.prepareList}" value="#{bundle.ViewLoginPageShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewLoginPageIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>